Update compile

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,59 +1,178 @@
-#!/bin/sh
+#!/usr/bin/env bash
+# bin/compile <build-dir> <cache-dir>
 
+# fail fast
 set -e
 
+# parse and derive params
 BUILD_DIR=$1
 CACHE_DIR=$2
+ENV_DIR=$3
+
+LP_DIR=`cd $(dirname $0); cd ..; pwd`
 
 # config
-VERSION=59.0
+VERSION=57.0.1
 LANG=en-US
 PLATFORM=linux64
 
-VERSION_GECKO=0.20.1
+VERSION_GECKO=0.19.1
 
 # Buildpack URL
-ARCHIVE_NAME=firefox
-ARCHIVE_NAME_GECKO=geckodriver
-FILE_NAME=${ARCHIVE_NAME}-${VERSION}.tar.bz2
-FILE_NAME_GECKO=${ARCHIVE_NAME_GECKO}-v${VERSION_GECKO}-${PLATFORM}.tar.gz
+ARCHIVE_NAME_FIREFOX=firefox
+ARCHIVE_NAME_GECKODRIVER=geckodriver
+FILE_NAME_FIREFOX=${ARCHIVE_NAME_FIREFOX}-${VERSION}.tar.bz2
+FILE_NAME_GECKODRIVER=${ARCHIVE_NAME_GECKODRIVER}-v${VERSION_GECKO}-${PLATFORM}.tar.gz
 BUILDPACK_FIREFOX_PACKAGE="https://download.mozilla.org/?product=firefox-${VERSION}-SSL&os=${PLATFORM}&lang=${LANG}"
-BUILDPACK_GECKODRIVER_PACKAGE="https://github.com/mozilla/geckodriver/releases/download/v${VERSION_GECKO}/${FILE_NAME_GECKO}"
+BUILDPACK_GECKODRIVER_PACKAGE="https://github.com/mozilla/geckodriver/releases/download/v${VERSION_GECKO}/${FILE_NAME_GECKODRIVER}"
 
+function error() {
+  echo " !     $*" >&2
+  exit 1
+}
 
+function topic() {
+  echo "-----> $*"
+}
+
+function indent() {
+  c='s/^/       /'
+  case $(uname) in
+    Darwin) sed -l "$c";;
+    *)      sed -u "$c";;
+  esac
+}
+
+stack=${STACK:-heroku-16}
+
+# Install correct dependencies according to $STACK
+case "$stack" in
+  "cedar-14")
+    PACKAGES="libxss1"
+    ;;
+  "heroku-16" | "heroku-18")
+    # the package list is found by using ci:debug then running ldd $GOOGLE_CHROME_BIN | grep not
+    # also look here for more packages/notes https://developers.google.com/web/tools/puppeteer/troubleshooting
+    PACKAGES="
+      libappindicator1
+      libasound2
+      libatk1.0-0
+      libatk-bridge2.0-0
+      libcairo-gobject2
+      libgconf-2-4
+      libgtk-3-0
+      libice6
+      libnspr4
+      libnss3
+      libsm6
+      libx11-xcb1
+      libxcomposite1
+      libxcursor1
+      libxdamage1
+      libxfixes3
+      libxi6
+      libxinerama1
+      libxrandr2
+      libxss1
+      libxt6
+      libxtst6
+      fonts-liberation
+    "
+    ;;
+  *)
+    error "STACK must be 'cedar-14', 'heroku-16', or 'heroku-18' not '$stack.'"
+esac
+
+if [ ! -f $CACHE_DIR/PURGED_CACHE_V1 ]; then
+  echo "-----> Purging cache"
+  rm -rf $CACHE_DIR/apt
+  rm -rf $CACHE_DIR/archives
+  rm -rf $CACHE_DIR/lists
+  touch $CACHE_DIR/PURGED_CACHE_V1
+fi
+
+echo "-----> Installing correct dependencies."
+
+APT_CACHE_DIR="$CACHE_DIR/apt/cache"
+APT_STATE_DIR="$CACHE_DIR/apt/state"
+
+mkdir -p "$APT_CACHE_DIR/archives/partial"
+mkdir -p "$APT_STATE_DIR/lists/partial"
+
+APT_OPTIONS="-o debug::nolocking=true -o dir::cache=$APT_CACHE_DIR -o dir::state=$APT_STATE_DIR"
+
+echo "-----> Updating apt caches"
+apt-get $APT_OPTIONS update | indent
+
+for PACKAGE in $PACKAGES; do
+  if [[ $PACKAGE == *deb ]]; then
+    PACKAGE_NAME=$(basename $PACKAGE .deb)
+    PACKAGE_FILE=$APT_CACHE_DIR/archives/$PACKAGE_NAME.deb
+
+    echo "-----> Fetching $PACKAGE"
+    curl -s -L -z $PACKAGE_FILE -o $PACKAGE_FILE $PACKAGE 2>&1 | indent
+  else
+    echo "-----> Fetching .debs for $PACKAGE"
+    apt-get $APT_OPTIONS -y --force-yes -d install --reinstall $PACKAGE | indent
+  fi
+done
+
+mkdir -p $BUILD_DIR/.apt
+
+for DEB in $(ls -1 $APT_CACHE_DIR/archives/*.deb); do
+  echo "-----> Installing $(basename $DEB)"
+  dpkg -x $DEB $BUILD_DIR/.apt/
+done
+
+# Install Firefox
 mkdir -p $CACHE_DIR
-if ! [ -e $CACHE_DIR/$FILE_NAME ]; then
+if ! [ -e $CACHE_DIR/$FILE_NAME_FIREFOX ]; then
   echo "-----> Fetching Firefox package from ${BUILDPACK_FIREFOX_PACKAGE}"
-  curl $BUILDPACK_FIREFOX_PACKAGE -L -o $CACHE_DIR/$FILE_NAME
+  curl $BUILDPACK_FIREFOX_PACKAGE -L -o $CACHE_DIR/$FILE_NAME_FIREFOX
 fi
 
-if ! [ -e $CACHE_DIR/$FILE_NAME_GECKO ]; then
+echo "-----> Extracting Firefox binaries to ${BUILD_DIR}/vendor/${ARCHIVE_NAME_FIREFOX}"
+mkdir -p $CACHE_DIR/$ARCHIVE_NAME_FIREFOX
+mkdir -p $BUILD_DIR/vendor
+tar jxf $CACHE_DIR/$FILE_NAME_FIREFOX -C $CACHE_DIR
+mv $CACHE_DIR/$ARCHIVE_NAME_FIREFOX $BUILD_DIR/vendor/
+
+# Install Geckodriver
+if ! [ -e $CACHE_DIR/$FILE_NAME_GECKODRIVER ]; then
   echo "-----> Fetching Geckodriver package from ${BUILDPACK_GECKODRIVER_PACKAGE}"
-  curl $BUILDPACK_GECKODRIVER_PACKAGE -L -o $CACHE_DIR/$FILE_NAME_GECKO
+  curl $BUILDPACK_GECKODRIVER_PACKAGE -L -o $CACHE_DIR/$FILE_NAME_GECKODRIVER
 fi
 
-echo "-----> Extracting Firefox binaries to ${BUILD_DIR}/vendor/${ARCHIVE_NAME}"
-echo "-----> INOF HOME: ${HOME}"
-mkdir -p $CACHE_DIR/$ARCHIVE_NAME
-mkdir -p $HOME/vendor
-tar jxf $CACHE_DIR/$FILE_NAME -C $CACHE_DIR
-mv $CACHE_DIR/$ARCHIVE_NAME $HOME/vendor/
+echo "-----> Extracting Geckodriver binaries to ${BUILD_DIR}/vendor/${ARCHIVE_NAME_GECKODRIVER}"
+mkdir -p $CACHE_DIR/$ARCHIVE_NAME_GECKODRIVER
+mkdir -p $BUILD_DIR/vendor/$ARCHIVE_NAME_GECKODRIVER
+tar -xzf $CACHE_DIR/$FILE_NAME_GECKODRIVER -C $CACHE_DIR
+mv $CACHE_DIR/$ARCHIVE_NAME_GECKODRIVER $BUILD_DIR/vendor/$ARCHIVE_NAME_GECKODRIVER/
 
-
-echo "-----> Extracting Geckodriver binaries to ${HOME}/vendor/${ARCHIVE_NAME_GECKO}"
-mkdir -p $CACHE_DIR/$ARCHIVE_NAME_GECKO
-mkdir -p $HOME/vendor/$ARCHIVE_NAME_GECKO
-tar -xzf $CACHE_DIR/$FILE_NAME_GECKO -C $CACHE_DIR
-mv $CACHE_DIR/$ARCHIVE_NAME_GECKO $HOME/vendor/$ARCHIVE_NAME_GECKO/
-
-echo "----> Creating DIR"
-mkdir -p $BUILD_DIR/.profile.d
 echo "----> Setting paths"
-cat <<EOF >$BUILD_DIR/.profile.d/000_paths.sh
-export PATH="\$HOME/vendor/firefox:\$HOME/vendor/geckodriver:\$PATH"
-export LD_LIBRARY_PATH="\$HOME/vendor/firefox:\$HOME/vendor/geckodriver:\$LD_LIBRARY_PATH"
-export LIBRARY_PATH="\$HOME/vendor/firefox:\$HOME/vendor/geckodriver:\$LIBRARY_PATH"
+mkdir -p $BUILD_DIR/.profile.d
+cat <<EOF >$BUILD_DIR/.profile.d/000_apt.sh
+export PATH="\$HOME/.apt/usr/bin:\$BUILD_DIR/vendor/firefox:\$BUILD_DIR/vendor/geckodriver:\$PATH"
+export LD_LIBRARY_PATH="\$HOME/.apt/usr/lib/x86_64-linux-gnu:\$HOME/.apt/usr/lib/i386-linux-gnu:\$HOME/.apt/usr/lib:\$BUILD_DIR/vendor/firefox:\$BUILD_DIR/vendor/geckodriver:\$LD_LIBRARY_PATH"
+export LIBRARY_PATH="\$HOME/.apt/usr/lib/x86_64-linux-gnu:\$HOME/.apt/usr/lib/i386-linux-gnu:\$HOME/.apt/usr/lib:\$BUILD_DIR/vendor/firefox:\$BUILD_DIR/vendor/geckodriver:\$LIBRARY_PATH"
+export INCLUDE_PATH="\$HOME/.apt/usr/include:\$HOME/.apt/usr/include/x86_64-linux-gnu:\$INCLUDE_PATH"
+export CPATH="\$INCLUDE_PATH"
+export CPPPATH="\$INCLUDE_PATH"
+export PKG_CONFIG_PATH="\$HOME/.apt/usr/lib/x86_64-linux-gnu/pkgconfig:\$HOME/.apt/usr/lib/i386-linux-gnu/pkgconfig:\$HOME/.apt/usr/lib/pkgconfig:\$PKG_CONFIG_PATH"
+export TMPDIR="\$BUILD_DIR/tmp"
 EOF
 
-echo "----> Setting paths completed"
+export PATH="$BUILD_DIR/.apt/usr/bin:$PATH:\$BUILD_DIR/vendor/firefox:\$BUILD_DIR/vendor/geckodriver:\$PATH"
+export LD_LIBRARY_PATH="$BUILD_DIR/.apt/usr/lib/x86_64-linux-gnu:$BUILD_DIR/.apt/usr/lib/i386-linux-gnu:$BUILD_DIR/.apt/usr/lib:\$BUILD_DIR/vendor/firefox:\$BUILD_DIR/vendor/geckodriver:\$LIBRARY_PATH"
+export LIBRARY_PATH="$BUILD_DIR/.apt/usr/lib/x86_64-linux-gnu:$BUILD_DIR/.apt/usr/lib/i386-linux-gnu:$BUILD_DIR/.apt/usr/lib:\$BUILD_DIR/vendor/firefox:\$BUILD_DIR/vendor/geckodriver:\$LIBRARY_PATH"
+export INCLUDE_PATH="$BUILD_DIR/.apt/usr/include:$BUILD_DIR/.apt/usr/include/x86_64-linux-gnu:$INCLUDE_PATH"
+export CPATH="$INCLUDE_PATH"
+export CPPPATH="$INCLUDE_PATH"
+export PKG_CONFIG_PATH="$BUILD_DIR/.apt/usr/lib/x86_64-linux-gnu/pkgconfig:$BUILD_DIR/.apt/usr/lib/i386-linux-gnu/pkgconfig:$BUILD_DIR/.apt/usr/lib/pkgconfig:$PKG_CONFIG_PATH"
+export TMPDIR="\$BUILD_DIR/tmp"
 
+#give environment to later buildpacks
+export | grep -E -e ' (PATH|LD_LIBRARY_PATH|LIBRARY_PATH|INCLUDE_PATH|CPATH|CPPPATH|PKG_CONFIG_PATH)='  > "$LP_DIR/export"
+
+echo "----> Rewrite package-config files"
+find $BUILD_DIR/.apt -type f -ipath '*/pkgconfig/*.pc' | xargs --no-run-if-empty -n 1 sed -i -e 's!^prefix=\(.*\)$!prefix='"$BUILD_DIR"'/.apt\1!g'
